name: flutter_application_1
description: "지구공 - 축구팀 관리 플랫폼"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # 🔥 Firebase 기본 (최신 버전)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3 # 푸시 알림
  firebase_analytics: ^11.3.3 # 사용자 분석
  firebase_crashlytics: ^4.1.3 # 크래시 리포트

  # 🔑 인증
  google_sign_in: ^6.2.2

  # 📸 미디어 & 파일
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1 # 이미지 캐싱
  path: ^1.9.0
  path_provider: ^2.1.4

  # 🔗 공유 & 링크
  share_plus: ^10.0.2
  url_launcher: ^6.3.1

  # 🎨 UI 컴포넌트
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^18.0.1 # 로컬 알림

  # 🌐 국제화 & 날짜
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # 📦 상태관리 & 아키텍처
  provider: ^6.1.2
  get_it: ^8.0.0 # 의존성 주입

  # 💾 데이터 저장
  shared_preferences: ^2.3.2
  hive: ^2.2.3 # 로컬 DB (빠른 캐싱)
  hive_flutter: ^1.1.0

  # 🌐 네트워킹
  dio: ^5.7.0 # HTTP 클라이언트
  connectivity_plus: ^6.0.5 # 네트워크 상태 체크

  # 🎯 유틸리티
  uuid: ^4.5.1 # 고유 ID 생성
  permission_handler: ^11.3.1 # 권한 관리
  device_info_plus: ^10.1.2 # 디바이스 정보
  package_info_plus: ^8.0.2 # 앱 정보

  # 📊 차트 & 그래프 (출석률, 통계용)
  fl_chart: ^0.69.0

  # 🎬 애니메이션
  lottie: ^3.1.2 # 로딩 애니메이션

  # 📋 폼 & 입력
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 🧪 테스트 도구
  mockito: ^5.4.4
  build_runner: ^2.4.13
  hive_generator: ^2.0.1 # Hive 모델 생성
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # 🌏 국제화 설정
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/default_profile.png

  fonts:
    - family: Pretendard # 한글 최적화 폰트
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
