// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRjLH6dH49fMvKUlrJqkHvAB0ZwbUZDAk',
    appId: '1:616861411729:web:781ad100f1d6dc821b5230',
    messagingSenderId: '616861411729',
    projectId: 'dgrr-dc7ed',
    authDomain: 'dgrr-dc7ed.firebaseapp.com',
    storageBucket: 'dgrr-dc7ed.firebasestorage.app',
    measurementId: 'G-MSZEHGVJE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDTgPRs3YvONulND9p7nc6tVr1fi-dNp4',
    appId: '1:616861411729:android:1f338412218609031b5230',
    messagingSenderId: '616861411729',
    projectId: 'dgrr-dc7ed',
    storageBucket: 'dgrr-dc7ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxJXQkHlY9ZAExoT_PaQYszxI_XttDFwI',
    appId: '1:616861411729:ios:fbc67bcb2276e53e1b5230',
    messagingSenderId: '616861411729',
    projectId: 'dgrr-dc7ed',
    storageBucket: 'dgrr-dc7ed.firebasestorage.app',
    iosClientId: '616861411729-b6hjihlhj0tk7fgu41hkc0hfieke1578.apps.googleusercontent.com',
    iosBundleId: 'com.example.dgrrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxJXQkHlY9ZAExoT_PaQYszxI_XttDFwI',
    appId: '1:616861411729:ios:fbc67bcb2276e53e1b5230',
    messagingSenderId: '616861411729',
    projectId: 'dgrr-dc7ed',
    storageBucket: 'dgrr-dc7ed.firebasestorage.app',
    iosClientId: '616861411729-b6hjihlhj0tk7fgu41hkc0hfieke1578.apps.googleusercontent.com',
    iosBundleId: 'com.example.dgrrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRjLH6dH49fMvKUlrJqkHvAB0ZwbUZDAk',
    appId: '1:616861411729:web:b03188cb2e9faed11b5230',
    messagingSenderId: '616861411729',
    projectId: 'dgrr-dc7ed',
    authDomain: 'dgrr-dc7ed.firebaseapp.com',
    storageBucket: 'dgrr-dc7ed.firebasestorage.app',
    measurementId: 'G-2KR2KJ1E8G',
  );
}
